version: '3'

services:
  db:
    container_name: 'HELPONGS-MySQL'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    healthcheck:
      test: "exit 0"
    ports: 
      - '12345:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=12345678
      - TZ=America/Sao_Paulo

  app:
    container_name: 'HELPONGS-Nodejs'
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    build: .
    command: yarn dev
    ports:
      - '3131:3131'
    volumes:
      - .:/usr/api
    
      